//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Industrial_Tools.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int id { get; set; }
        public int id_usuario { get; set; }
        public string mensaje { get; set; }
        public int status { get; set; }
        public int tipo_mensaje { get; set; }
        public System.DateTime fecha { get; set; }
    }
}
