//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Industrial_Tools.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string email { get; set; }
        public string mensaje { get; set; }
        public string telefono { get; set; }
    }
}
