//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Industrial_Tools.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellido_paterno { get; set; }
        public string apellido_materno { get; set; }
        public string correo { get; set; }
        public string pass { get; set; }
        public int status { get; set; }
        public int role_id { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public string telefono { get; set; }
        public string username { get; set; }
    }
}
