//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Industrial_Tools.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public int id_usuario { get; set; }
        public decimal sub_total { get; set; }
        public decimal iva { get; set; }
        public decimal total { get; set; }
        public int id_pago { get; set; }
        public decimal stat { get; set; }
    }
}
